### ISSUE TITLE
SmartParam fails to start from a executable JAR created by Spring Boot

### ISSUE THREAD

**Issue by mkaluzny** [smartparam/smartparam#26]
SmartParam fails to start from an executable JAR created by Spring Boot. Here is the error thrown at startup:
```
Caused by: java.lang.AssertionError: Not a File: file:/.../some-jar.jar!/lib/smartparam-engine-1.1.3-SNAPSHOT.jar
        at eu.infomas.annotation.AnnotationDetector.detect(AnnotationDetector.java:297)
        at org.kielo.annotationscanner.ReflectionsScanner.runDetector(ReflectionsScanner.java:58)
        at org.kielo.annotationscanner.ReflectionsScanner.findClassesAnnotatedWith(ReflectionsScanner.java:36)
        at org.smartparam.engine.annotated.scanner.AnnotatedObjectsScanner.getAnnotatedObjects(AnnotatedObjectsScanner.java:75)
        at org.smartparam.engine.annotated.scanner.PackageTypeScanner.scanTypes(PackageTypeScanner.java:40)
        at org.smartparam.engine.annotated.repository.ScanningMatcherRepository.scanAnnotations(ScanningMatcherRepository.java:39)
        at org.smartparam.engine.annotated.initialization.TypeScannerInitializer.initializeObject(TypeScannerInitializer.java:48)
        at org.smartparam.engine.config.initialization.BasicComponentInitializerRunner.runInitializers(BasicComponentInitializerRunner.java:41)
        at org.smartparam.engine.config.initialization.BasicComponentInitializerRunner.runInitializersOnList(BasicComponentInitializerRunner.java:33)
        at org.smartparam.engine.config.ParamEngineFactory.createParamEngine(ParamEngineFactory.java:69)
        at org.smartparam.engine.config.ParamEngineFactory.paramEngine(ParamEngineFactory.java:50)
```

**Comment by adamdubiel** [comment]
I reproduced an analysed the problem and it is not a trivial one. The library used to scan annotations [Ifomas ASL](https://github.com/rmuller/infomas-asl) does not work well with jars inside jars, which is what Spring Boot executable jar actually is. I will probably need to hack some things in this library.

Just to get thing rolling you could disable annotation scanning (`ParamEngineConfigBuilder#withAnnotationScanDisabled`), but it will force you to register all default components by hand. I can give you code snippet that should cover all defaults if this is a pressing matter.

**Comment by adamdubiel** [comment]
Okay, so i think the best way to solve it is giving choice wether to use current annotation scanner vs sth like Spring annotation scanner in `smartparam-spring`.

**Comment by adamdubiel** [comment]
@mkaluzny any followup on this?

**Comment by tomekkup** [comment]
Upgrade to never version of infomas-asl. It solved this problem on my side

**Comment by adamdubiel** [comment]
Oh, great! I will release new version with updated dep.

**Comment by aogorek** [comment]
Hello @adamdubiel, can You please do the relase? I need it too :)
